iris_classification/estimator/urls.py
from django.urls import path
from . import views


app_name = 'estimator'
urlpatterns = [
	path('', views.home, name='home'),
	path('dataset/', views.dataset, name='dataset'),
	path('predict/', views.predict, name='predict'),
]

iris_classification/iris_classification/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('estimator.urls')),
    path('admin/', admin.site.urls),
]

iris_classification/estimator/models.py
from django.db import models

# Create your models here.

iris_classification/estimator/forms.py
from django import forms

class PredictionForm(forms.Form):
	sepal_length = forms.CharField(label='Sepal Length')
	sepal_width = forms.CharField(label='Sepal Width')
	petal_length = forms.CharField(label='Petal Length')
	petal_width = forms.CharField(label='Petal Width')

iris_classification/estimator/views.py
import numpy as np
from django.shortcuts import render
from .forms import PredictionForm
from .classifier import make_prediction


def home(request):
	return render(request, 'estimator/home.html')

def dataset(request):
	return render(request, 'estimator/dataset.html', {'title': 'Dataset'})

def predict(request):
	if request.method == 'POST':
		form = PredictionForm(request.POST)
		if form.is_valid():
			pred_sepal_length = float(form.cleaned_data['sepal_length'])
			pred_sepal_width = float(form.cleaned_data['sepal_width'])
			pred_petal_length = float(form.cleaned_data['petal_length'])
			pred_petal_width = float(form.cleaned_data['petal_width'])
			arr = [float(form.cleaned_data[key]) for key in form.cleaned_data.keys()]
			arr = np.array(arr).reshape(1, -1)
			prediction = make_prediction(arr)
			print("Prediction: ", prediction)
	else:
		form = PredictionForm()
		prediction = ''
	return render(request, 'estimator/predict.html', {'form': form, 'prediction': prediction})

iris_classification/estimator/templates/estimator/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<!-- css style -->
  <link rel="stylesheet" type="text/css" href="{% static 'estimator/style.css' %}">

  <!-- icon -->
  <link rel="shortcut icon" href="{% static 'estimator/icon/icon.png' %}" type="image/x-icon">
	<link rel="icon" href="{% static 'estimator/icon/icon.png' %}" type="image/x-icon">

	<!-- Google Font -->
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans&display=swap" rel="stylesheet"> 
	
	{% if title %}
		<title>Iris - {{ title }}</title>
	{% else %}
		<title>Iris Classification</title>
	{% endif %}
</head>
<body>

<!-- navigation bar -->
<header class="mb-4">
	<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
	  <div class="container">
		<a class="navbar-brand" href="{% url 'estimator:home' %}">
	    <img src="{% static 'estimator/icon/brand_icon.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="Iris Brand">
	    IRIS
	  </a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNav">
	  	<div class="navbar-nav mr-auto">
				<a href="{% url 'estimator:home' %}" class="nav-item nav-link">Home</a>
				<a href="{% url 'estimator:dataset' %}" class="nav-item nav-link">Dataset</a>
				<a href="{% url 'estimator:predict' %}" class="nav-item nav-link">Predict</a>
			</div>
	  </div>
	</div>
	</nav>
</header>

<main role="main" class="container">
	<div class="row justify-content-center">
		<div class="col-md-10">
			{% block content %}{% endblock %}
		</div>
	</div>
</main>
	
</body>
</html>

iris_classification/estimator/templates/estimator/home.html
{% extends "estimator/base.html" %}
{% load static %}
{% block content %}
	<h1 class="home-title border-bottom pb-2">Iris Classification</h1>
	<h2>Introduction</h2>

	<p>Quoted from <a href="https://en.wikipedia.org/wiki/Iris_flower_data_set" target="_blank">Iris flower data set</a></p>

	<div class="home-container-1">
		<img src="{% static 'estimator/home_imgs/iris_baby_blue.jpg' %}" alt="Iris Baby Blue" width="300" height="250">

		<p>The Iris flower data set or Fisher's Iris data set is a multivariate data set introduced by the British statistician and biologist Ronald Fisher in his 1936 paper The use of multiple measurements in taxonomic problems as an example of linear discriminant analysis. It is sometimes called Anderson's Iris data set because Edgar Anderson collected the data to quantify the morphologic variation of Iris flowers of three related species. Two of the three species were collected in the Gaspé Peninsula "all from the same pasture, and picked on the same day and measured at the same time by the same person with the same apparatus".</p>
	</div>

	<div class="home-container-2">
		<div>
			<p>The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters. Based on the combination of these four features, Fisher developed a linear discriminant model to distinguish the species from each other.</p>

			<p>A sepal is a part of the flower of angiosperms (flowering plants). Usually green, sepals typically function as protection for the flower in bud, and often as support for the petals when in bloom. Petals are modified leaves that surround the reproductive parts of flowers. They are often brightly colored or unusually shaped to attract pollinators.</p>
		</div>

		<img src="{% static 'estimator/home_imgs/iris_virginica_virginica_lg.jpg' %}" alt="Iris Virginica" width="300" height="250">
	</div>
	
{% endblock content %}

iris_classification/estimator/templates/estimator/predict.html
{% extends "estimator/base.html" %}
{% load widget_tweaks %}
{% block content %}
<div class="content-section row">
	<div class="col-7">
		<legend class="border-bottom mb-4">Fill Below:</legend>
		<form method="POST" action="{% url 'estimator:predict' %}">
		{% csrf_token %}
		<div class="form-group">
			<label for="id_sepal_length" class="form-control-label">{{ form.sepal_length.label }}</label>
			{% if form.sepal_length.errors %}
				{{ form.sepal_length|add_class:'form-control form-control-md is-invalid' }}
				<div class="invalid-feedback">
					{% for error in form.sepal_length.errors %}
						<span>{{ error }}</span>
					{% endfor %}
				</div>
			{% else %}
				{{ form.sepal_length|add_class:'form-control form-control-md' }}
			{% endif %}
		</div>
		<div class="form-group">
			<label for="id_sepal_width" class="form-control-label">{{ form.sepal_width.label }}</label>
			{% if form.sepal_width.errors %}
				{{ form.sepal_width|add_class:'form-control form-control-md is-invalid' }}
				<div class="invalid-feedback">
					{% for error in form.sepal_width.errors %}
						<span>{{ error }}</span>
					{% endfor %}
				</div>
			{% else %}
				{{ form.sepal_width|add_class:'form-control form-control-md' }}
			{% endif %}
		</div>
		<div class="form-group">
			<label for="id_petal_length" class="form-control-label">{{ form.petal_length.label }}</label>
			{% if form.petal_length.errors %}
				{{ form.petal_length|add_class:'form-control form-control-md is-invalid' }}
				<div class="invalid-feedback">
					{% for error in form.petal_length.errors %}
						<span>{{ error }}</span>
					{% endfor %}
				</div>
			{% else %}
				{{ form.petal_length|add_class:'form-control form-control-md' }}
			{% endif %}
		</div>
		<div class="form-group">
			<label for="id_petal_width" class="form-control-label">{{ form.petal_width.label }}</label>
			{% if form.petal_width.errors %}
				{{ form.petal_width|add_class:'form-control form-control-md is-invalid' }}
				<div class="invalid-feedback">
					{% for error in form.petal_width.errors %}
						<span>{{ error }}</span>
					{% endfor %}
				</div>
			{% else %}
				{{ form.petal_width|add_class:'form-control form-control-md' }}
			{% endif %}
		</div>
		<div class="form-group">
			<input class="btn btn-outline-info" type="submit" value="Submit">
		</div>
	</form>
	</div>

	<div class="ml-4 col-4">
		<legend class="border-bottom mb-4 text-center">The Prediction</legend>
		{% if prediction %}
			<p class="predict-text text-center">{{ prediction }}</p>
		{% else %}
			<p class="predict-text text-center">Result is here!</p>
		{% endif %}
	</div>
</div>
{% endblock content %}